#!/usr/bin/env bash
# Lisp-Claw Docker Setup Script
# Usage: ./scripts/docker-setup.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"
IMAGE_NAME="${LISP_CLAW_IMAGE:-lisp-claw:local}"

# Configuration directories
LISP_CLAW_CONFIG_DIR="${LISP_CLAW_CONFIG_DIR:-$HOME/.lisp-claw}"
LISP_CLAW_WORKSPACE_DIR="${LISP_CLAW_WORKSPACE_DIR:-$HOME/.lisp-claw/workspace}"

# Gateway settings
LISP_CLAW_GATEWAY_PORT="${LISP_CLAW_GATEWAY_PORT:-18789}"
LISP_CLAW_GATEWAY_BIND="${LISP_CLAW_GATEWAY_BIND:-0.0.0.0}"

# Timezone
LISP_CLAW_TZ="${LISP_CLAW_TZ:-UTC}"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing dependency: $1" >&2
    exit 1
  fi
}

# Validate dependencies
require_cmd docker
if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose not available" >&2
  exit 1
fi

# Create config directories
mkdir -p "$LISP_CLAW_CONFIG_DIR"
mkdir -p "$LISP_CLAW_WORKSPACE_DIR"

# Generate gateway token if not provided
if [[ -z "${LISP_CLAW_GATEWAY_TOKEN:-}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    LISP_CLAW_GATEWAY_TOKEN="$(openssl rand -hex 32)"
  else
    LISP_CLAW_GATEWAY_TOKEN="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
  fi
fi

export LISP_CLAW_CONFIG_DIR
export LISP_CLAW_WORKSPACE_DIR
export LISP_CLAW_GATEWAY_PORT
export LISP_CLAW_GATEWAY_BIND
export LISP_CLAW_GATEWAY_TOKEN
export LISP_CLAW_IMAGE
export LISP_CLAW_TZ

# Build or pull image
echo "==> Building Docker image: $IMAGE_NAME"
docker build -t "$IMAGE_NAME" -f "$ROOT_DIR/Dockerfile" "$ROOT_DIR"

# Create .env file for future runs
ENV_FILE="$ROOT_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Lisp-Claw Environment Configuration
# Generated by docker-setup.sh

LISP_CLAW_CONFIG_DIR=$LISP_CLAW_CONFIG_DIR
LISP_CLAW_WORKSPACE_DIR=$LISP_CLAW_WORKSPACE_DIR
LISP_CLAW_GATEWAY_PORT=$LISP_CLAW_GATEWAY_PORT
LISP_CLAW_GATEWAY_BIND=$LISP_CLAW_GATEWAY_BIND
LISP_CLAW_GATEWAY_TOKEN=$LISP_CLAW_GATEWAY_TOKEN
LISP_CLAW_IMAGE=$IMAGE_NAME
LISP_CLAW_TZ=$LISP_CLAW_TZ

# AI Provider API Keys (uncomment and set as needed)
# ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY=sk-...
EOF

echo ""
echo "==> Lisp-Claw Docker Setup Complete"
echo ""
echo "Configuration:"
echo "  Config directory: $LISP_CLAW_CONFIG_DIR"
echo "  Workspace: $LISP_CLAW_WORKSPACE_DIR"
echo "  Gateway port: $LISP_CLAW_GATEWAY_PORT"
echo "  Gateway bind: $LISP_CLAW_GATEWAY_BIND"
echo "  Gateway token: $LISP_CLAW_GATEWAY_TOKEN"
echo ""
echo "Commands:"
echo "  Start:     docker compose -f $COMPOSE_FILE up -d lisp-claw-gateway"
echo "  Logs:      docker compose -f $COMPOSE_FILE logs -f lisp-claw-gateway"
echo "  Stop:      docker compose -f $COMPOSE_FILE down"
echo "  REPL:      docker compose -f $COMPOSE_FILE run --rm lisp-claw-repl"
echo ""
echo "WebSocket API:"
echo "  ws://127.0.0.1:$LISP_CLAW_GATEWAY_PORT/"
echo ""
echo "Health check:"
echo "  curl http://127.0.0.1:$LISP_CLAW_GATEWAY_PORT/healthz"
echo ""

# Start gateway
echo "==> Starting Lisp-Claw gateway"
docker compose -f "$COMPOSE_FILE" up -d lisp-claw-gateway

echo ""
echo "Gateway starting..."
sleep 3

# Check health
if curl -fsS "http://127.0.0.1:$LISP_CLAW_GATEWAY_PORT/healthz" >/dev/null 2>&1; then
  echo "Gateway is healthy and running!"
else
  echo "Gateway may still be starting. Check logs with:"
  echo "  docker compose -f $COMPOSE_FILE logs -f lisp-claw-gateway"
fi
